apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stellar-lense.fullname" . }}
  labels:
    {{- include "stellar-lense.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.STELLARLENSE_SERVICE_SECRET_KEY }}
  STELLARLENSE_SERVICE_SECRET_KEY: {{ .Values.secrets.STELLARLENSE_SERVICE_SECRET_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.STELLARLENSE_MODEL_SIGNING_KEY }}
  STELLARLENSE_MODEL_SIGNING_KEY: {{ .Values.secrets.STELLARLENSE_MODEL_SIGNING_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.STELLARLENSE_ADMIN_API_KEY }}
  STELLARLENSE_ADMIN_API_KEY: {{ .Values.secrets.STELLARLENSE_ADMIN_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.STELLARLENSE_COMPLIANCE_API_KEY }}
  STELLARLENSE_COMPLIANCE_API_KEY: {{ .Values.secrets.STELLARLENSE_COMPLIANCE_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.STELLARLENSE_WEBHOOK_ENCRYPTION_KEY }}
  STELLARLENSE_WEBHOOK_ENCRYPTION_KEY: {{ .Values.secrets.STELLARLENSE_WEBHOOK_ENCRYPTION_KEY | b64enc | quote }}
  {{- end }}
