"""Threshold Tuning CLI — Issue #535.

Runs data-driven threshold tuning workflows for LedgerLens anomaly alerts and
writes calibrated threshold recommendations to ``reports/threshold_tuning/``.

Three strategies are available (see ``detection/threshold_tuner.py`` for
methodology):

  precision_recall     — maximise F-beta score (default β=1.0)
  false_positive_budget — highest recall while keeping FPR ≤ budget
  cost_sensitive       — minimise FP_weight·FP + FN_weight·FN

Input can be:
  1. A backtest report JSON (``reports/backtest_*.json``) — uses the
     per-wallet scores and ground-truth labels already in the report.
  2. A Parquet/CSV evaluation dataset with ``risk_score`` and ``label`` columns.
  3. The synthetic labelled dataset generated by
     ``scripts/generate_synthetic_dataset.py`` (default fallback).

Usage::

    # Tune from the latest backtest report (auto-detected)
    python -m scripts.tune_alert_thresholds

    # Tune from an explicit evaluation file
    python -m scripts.tune_alert_thresholds \\
        --eval-data reports/backtest_h1_2024.json \\
        --strategy all \\
        --beta 0.5

    # Tune from a labelled parquet dataset
    python -m scripts.tune_alert_thresholds \\
        --eval-data data/synthetic_dataset.parquet \\
        --score-col risk_score \\
        --label-col label \\
        --strategy false_positive_budget \\
        --max-fpr 0.03

Exit codes:
    0 — tuning completed, report written
    1 — tuning completed but no threshold change from current default
    2 — fatal error
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

from detection.threshold_tuner import ThresholdTuner, save_tuning_report
from utils.logging import get_logger

logger = get_logger(__name__)

DEFAULT_THRESHOLD = 70
REPORTS_DIR = Path("reports/threshold_tuning")
BACKTEST_REPORTS_DIR = Path("reports")


# ---------------------------------------------------------------------------
# Input loaders
# ---------------------------------------------------------------------------


def _load_from_backtest_json(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Extract (scores, labels) from a backtest report JSON."""
    data = json.loads(path.read_text())

    # Format A: top-level "wallet_results" list with score/label dicts
    if "wallet_results" in data:
        rows = data["wallet_results"]
        scores = np.array([float(r.get("score", r.get("risk_score", 0))) for r in rows])
        labels = np.array([int(r.get("label", r.get("ground_truth", 0))) for r in rows])
        return scores, labels

    # Format B: "campaigns" list — each campaign has a detection score and known status
    if "campaigns" in data:
        rows = data["campaigns"]
        scores = np.array([float(r.get("peak_score", r.get("score", 0))) for r in rows])
        labels = np.ones(len(rows), dtype=int)  # all campaigns are known wash-trade events
        return scores, labels

    raise ValueError(
        f"Cannot extract (scores, labels) from backtest report {path} — "
        "expected 'wallet_results' or 'campaigns' key"
    )


def _load_from_tabular(
    path: Path,
    score_col: str = "risk_score",
    label_col: str = "label",
) -> tuple[np.ndarray, np.ndarray]:
    """Load (scores, labels) from a Parquet or CSV file."""
    import pandas as pd

    if path.suffix == ".parquet":
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if score_col not in df.columns:
        raise ValueError(f"Score column '{score_col}' not found in {path}")
    if label_col not in df.columns:
        raise ValueError(f"Label column '{label_col}' not found in {path}")

    valid = df[[score_col, label_col]].dropna()
    scores = valid[score_col].to_numpy(dtype=float)
    labels = valid[label_col].to_numpy(dtype=int)
    return scores, labels


def _load_synthetic_fallback() -> tuple[np.ndarray, np.ndarray]:
    """Load scores/labels from the synthetic dataset by running inference."""
    import pandas as pd

    from detection.model_inference import RiskScorer

    data_path = Path("data/synthetic_dataset.parquet")
    if not data_path.exists():
        raise FileNotFoundError(
            f"Synthetic dataset not found at {data_path}. "
            "Run: python -m scripts.generate_synthetic_dataset"
        )

    df = pd.read_parquet(data_path)
    labels = df["label"].to_numpy(dtype=int)

    scorer = RiskScorer()
    feature_df = df.drop(columns=["label"], errors="ignore")
    scores_list: list[float] = []
    for _, row in feature_df.iterrows():
        try:
            result = scorer.score(row.to_frame().T)
            scores_list.append(float(result.get("score", 0)))
        except Exception:  # noqa: BLE001
            scores_list.append(0.0)

    return np.array(scores_list), labels


# ---------------------------------------------------------------------------
# Auto-detect the latest backtest report
# ---------------------------------------------------------------------------


def _find_latest_backtest() -> Path | None:
    candidates = sorted(BACKTEST_REPORTS_DIR.glob("backtest_*.json"), reverse=True)
    return candidates[0] if candidates else None


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Tune LedgerLens alert thresholds from evaluation data.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--eval-data", "-d", default=None,
        help="Path to evaluation data (backtest JSON, Parquet, or CSV). "
             "Auto-detects latest backtest report if not specified.",
    )
    p.add_argument(
        "--score-col", default="risk_score",
        help="Name of the score column when using tabular data (default: risk_score).",
    )
    p.add_argument(
        "--label-col", default="label",
        help="Name of the label column when using tabular data (default: label).",
    )
    p.add_argument(
        "--strategy",
        choices=["precision_recall", "false_positive_budget", "cost_sensitive", "all"],
        default="all",
        help="Tuning strategy to run (default: all).",
    )
    p.add_argument(
        "--beta", type=float, default=1.0,
        help="Beta for F-beta score in precision_recall strategy (default: 1.0).",
    )
    p.add_argument(
        "--max-fpr", type=float, default=0.05,
        help="Max false-positive rate for false_positive_budget strategy (default: 0.05).",
    )
    p.add_argument(
        "--fp-weight", type=float, default=1.0,
        help="FP cost weight for cost_sensitive strategy (default: 1.0).",
    )
    p.add_argument(
        "--fn-weight", type=float, default=5.0,
        help="FN cost weight for cost_sensitive strategy (default: 5.0).",
    )
    p.add_argument(
        "--output-dir", default=str(REPORTS_DIR),
        help=f"Output directory for reports (default: {REPORTS_DIR}).",
    )
    p.add_argument(
        "--no-markdown", action="store_true",
        help="Skip generating Markdown report files.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    output_dir = Path(args.output_dir)

    # ------------------------------------------------------------------
    # Load data
    # ------------------------------------------------------------------
    scores: np.ndarray | None = None
    labels: np.ndarray | None = None

    if args.eval_data:
        path = Path(args.eval_data)
        try:
            if path.suffix == ".json":
                scores, labels = _load_from_backtest_json(path)
            else:
                scores, labels = _load_from_tabular(path, args.score_col, args.label_col)
            logger.info(
                "Loaded %d evaluation samples from %s", len(scores), path
            )
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to load eval data from %s: %s", path, exc)
            return 2

    if scores is None:
        # Try auto-detecting a backtest report
        latest = _find_latest_backtest()
        if latest:
            try:
                scores, labels = _load_from_backtest_json(latest)
                logger.info("Auto-detected backtest report: %s (%d samples)", latest, len(scores))
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not load auto-detected backtest report: %s", exc)

    if scores is None:
        logger.info("No eval data found — falling back to synthetic dataset + RiskScorer")
        try:
            scores, labels = _load_synthetic_fallback()
        except Exception as exc:  # noqa: BLE001
            logger.error("Synthetic fallback failed: %s", exc)
            return 2

    assert labels is not None
    if len(scores) == 0:
        logger.error("Evaluation dataset is empty")
        return 2

    pos = int(labels.sum())
    logger.info(
        "Evaluation set: %d samples, %d positives (%.1f%%)",
        len(scores), pos, 100 * pos / len(scores),
    )

    # ------------------------------------------------------------------
    # Run tuning
    # ------------------------------------------------------------------
    try:
        tuner = ThresholdTuner(scores=scores, labels=labels)
    except ValueError as exc:
        logger.error("Cannot create ThresholdTuner: %s", exc)
        return 2

    strategies_to_run: list[str] = (
        ["precision_recall", "false_positive_budget", "cost_sensitive"]
        if args.strategy == "all"
        else [args.strategy]
    )

    recommendations: dict[str, int] = {}
    for strategy in strategies_to_run:
        try:
            if strategy == "precision_recall":
                result = tuner.tune_precision_recall(beta=args.beta)
            elif strategy == "false_positive_budget":
                result = tuner.tune_false_positive_budget(max_fpr=args.max_fpr)
            else:
                result = tuner.tune_cost_sensitive(
                    fp_weight=args.fp_weight,
                    fn_weight=args.fn_weight,
                )
        except Exception as exc:  # noqa: BLE001
            logger.error("Tuning strategy '%s' failed: %s", strategy, exc)
            continue

        save_tuning_report(result, output_dir=output_dir, also_markdown=not args.no_markdown)
        recommendations[strategy] = result.recommended_threshold
        print(
            f"[tune] {strategy}: recommended threshold = {result.recommended_threshold}"
        )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    if not recommendations:
        logger.error("No tuning results produced")
        return 2

    print(f"\n[tune] Current default threshold: {DEFAULT_THRESHOLD}")
    any_change = any(v != DEFAULT_THRESHOLD for v in recommendations.values())

    if any_change:
        print("[tune] Threshold change(s) recommended:")
        for strat, val in recommendations.items():
            delta = val - DEFAULT_THRESHOLD
            sign = "+" if delta >= 0 else ""
            print(f"  {strat}: {val} ({sign}{delta} vs current {DEFAULT_THRESHOLD})")
        print(
            f"\n  To apply a recommendation, set RISK_SCORE_FLAG_THRESHOLD=<value> "
            f"in your environment or config.py."
        )
        return 0
    else:
        print(f"[tune] All strategies agree: keep current threshold at {DEFAULT_THRESHOLD}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
