// Generated by tools/schema-gen from the Soroban contract-spec of
// contracts/ledgerlens-score/src/types.rs (`RiskScore`). Do not edit by hand.
// Fields are in contract-spec (XDR) order — alphabetical, matching the on-chain spec.
export interface RiskScore {
  benford_flag: boolean;
  /** @minimum 0 @maximum 100 */
  benford_score: number;
  commitment: string | null;
  /** @minimum 0 @maximum 100 */
  confidence: number;
  ml_flag: boolean;
  /** @minimum 0 @maximum 100 */
  ml_score: number;
  model_version: number;
  /** @minimum 0 @maximum 100 */
  network_score: number;
  /** @minimum 0 @maximum 100 */
  score: number;
  timestamp: number;
}
// JSON-Schema twin: risk_score.schema.json
