# Generated by tools/schema-gen from the Soroban contract-spec of
# contracts/ledgerlens-score/src/types.rs (`RiskScore`). Do not edit by hand.
# Fields are in contract-spec (XDR) order — alphabetical, matching the on-chain spec.
# Requires: pydantic>=2.0

from pydantic import BaseModel, Field
from typing import Optional

# JSON-Schema twin: risk_score.schema.json
class RiskScore(BaseModel):
    benford_flag: bool
    benford_score: int = Field(ge=0, le=100)
    commitment: Optional[str] = None
    confidence: int = Field(ge=0, le=100)
    ml_flag: bool
    ml_score: int = Field(ge=0, le=100)
    model_version: int
    network_score: int = Field(ge=0, le=100)
    score: int = Field(ge=0, le=100)
    timestamp: int
