apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: stellar-lense-redis-partition
  namespace: chaos-mesh
spec:
  action: partition
  mode: all
  selector:
    namespaces: ["stellar-lense-staging"]
    labelSelectors:
      "app.kubernetes.io/component": api
  direction: to
  target:
    selector:
      namespaces: ["stellar-lense-staging"]
      labelSelectors:
        "app.kubernetes.io/name": redis
    mode: all
  duration: "60s"
