apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: stellar-lense-api-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: ["stellar-lense-staging"]
    labelSelectors:
      "app.kubernetes.io/component": api
  scheduler:
    cron: "@every 10m"
  duration: "30s"
